CREATE UNIQUE INDEX alternative_release_gid ON alternative_release(gid);
CREATE UNIQUE INDEX alternative_release_type_gid ON alternative_release_type(gid);
CREATE UNIQUE INDEX alternative_medium_track_pkey ON alternative_medium_track(alternative_medium, track);
CREATE UNIQUE INDEX area_type_gid ON area_type(gid);
CREATE UNIQUE INDEX area_gid ON area(gid);
CREATE UNIQUE INDEX area_gid_redirect_pkey ON area_gid_redirect(gid);
CREATE UNIQUE INDEX area_gid_redirect_gid ON area_gid_redirect(gid);
CREATE UNIQUE INDEX area_alias_type_gid ON area_alias_type(gid);
CREATE UNIQUE INDEX area_annotation_pkey ON area_annotation(area, annotation);
CREATE UNIQUE INDEX area_attribute_type_gid ON area_attribute_type(gid);
CREATE UNIQUE INDEX area_attribute_type_allowed_value_gid ON area_attribute_type_allowed_value(gid);
CREATE UNIQUE INDEX area_containment_pkey ON area_containment(descendant, parent);
CREATE UNIQUE INDEX area_tag_pkey ON area_tag(area, tag);
CREATE UNIQUE INDEX area_tag_raw_pkey ON area_tag_raw(area, editor, tag);
CREATE UNIQUE INDEX artist_gid ON artist(gid);
CREATE INDEX artist_discogs_artist_id ON artist(discogs_artist_id);
CREATE UNIQUE INDEX artist_alias_type_gid ON artist_alias_type(gid);
CREATE UNIQUE INDEX artist_annotation_pkey ON artist_annotation(artist, annotation);
CREATE UNIQUE INDEX artist_attribute_type_gid ON artist_attribute_type(gid);
CREATE UNIQUE INDEX artist_attribute_type_allowed_value_gid ON artist_attribute_type_allowed_value(gid);
CREATE UNIQUE INDEX artist_ipi_pkey ON artist_ipi(artist, ipi);
CREATE UNIQUE INDEX artist_isni_pkey ON artist_isni(artist, isni);
CREATE UNIQUE INDEX artist_tag_pkey ON artist_tag(artist, tag);
CREATE UNIQUE INDEX artist_rating_raw_pkey ON artist_rating_raw(artist, editor);
CREATE UNIQUE INDEX artist_tag_raw_pkey ON artist_tag_raw(artist, editor, tag);
CREATE UNIQUE INDEX artist_credit_gid ON artist_credit(gid);
CREATE UNIQUE INDEX artist_credit_gid_redirect_pkey ON artist_credit_gid_redirect(gid);
CREATE UNIQUE INDEX artist_credit_gid_redirect_gid ON artist_credit_gid_redirect(gid);
CREATE UNIQUE INDEX artist_credit_name_pkey ON artist_credit_name(artist_credit, position);
CREATE UNIQUE INDEX artist_gid_redirect_pkey ON artist_gid_redirect(gid);
CREATE UNIQUE INDEX artist_gid_redirect_gid ON artist_gid_redirect(gid);
CREATE UNIQUE INDEX artist_type_gid ON artist_type(gid);
CREATE UNIQUE INDEX deleted_entity_pkey ON deleted_entity(gid);
CREATE UNIQUE INDEX deleted_entity_gid ON deleted_entity(gid);
CREATE UNIQUE INDEX edit_note_recipient_pkey ON edit_note_recipient(recipient, edit_note);
CREATE UNIQUE INDEX edit_area_pkey ON edit_area(edit, area);
CREATE UNIQUE INDEX edit_artist_pkey ON edit_artist(edit, artist);
CREATE UNIQUE INDEX edit_event_pkey ON edit_event(edit, event);
CREATE UNIQUE INDEX edit_genre_pkey ON edit_genre(edit, genre);
CREATE UNIQUE INDEX edit_instrument_pkey ON edit_instrument(edit, instrument);
CREATE UNIQUE INDEX edit_label_pkey ON edit_label(edit, label);
CREATE UNIQUE INDEX edit_mood_pkey ON edit_mood(edit, mood);
CREATE UNIQUE INDEX edit_place_pkey ON edit_place(edit, place);
CREATE UNIQUE INDEX edit_release_pkey ON edit_release(edit, release);
CREATE UNIQUE INDEX edit_release_group_pkey ON edit_release_group(edit, release_group);
CREATE UNIQUE INDEX edit_recording_pkey ON edit_recording(edit, recording);
CREATE UNIQUE INDEX edit_series_pkey ON edit_series(edit, series);
CREATE UNIQUE INDEX edit_work_pkey ON edit_work(edit, work);
CREATE UNIQUE INDEX edit_url_pkey ON edit_url(edit, url);
CREATE UNIQUE INDEX editor_language_pkey ON editor_language(editor, language);
CREATE UNIQUE INDEX editor_subscribe_artist_deleted_pkey ON editor_subscribe_artist_deleted(editor, gid);
CREATE UNIQUE INDEX editor_subscribe_artist_deleted_gid ON editor_subscribe_artist_deleted(gid);
CREATE UNIQUE INDEX editor_subscribe_label_deleted_pkey ON editor_subscribe_label_deleted(editor, gid);
CREATE UNIQUE INDEX editor_subscribe_label_deleted_gid ON editor_subscribe_label_deleted(gid);
CREATE UNIQUE INDEX editor_subscribe_series_deleted_pkey ON editor_subscribe_series_deleted(editor, gid);
CREATE UNIQUE INDEX editor_subscribe_series_deleted_gid ON editor_subscribe_series_deleted(gid);
CREATE UNIQUE INDEX event_gid ON event(gid);
CREATE UNIQUE INDEX event_rating_raw_pkey ON event_rating_raw(event, editor);
CREATE UNIQUE INDEX event_tag_raw_pkey ON event_tag_raw(event, editor, tag);
CREATE UNIQUE INDEX event_alias_type_gid ON event_alias_type(gid);
CREATE UNIQUE INDEX event_annotation_pkey ON event_annotation(event, annotation);
CREATE UNIQUE INDEX event_attribute_type_gid ON event_attribute_type(gid);
CREATE UNIQUE INDEX event_attribute_type_allowed_value_gid ON event_attribute_type_allowed_value(gid);
CREATE UNIQUE INDEX event_gid_redirect_pkey ON event_gid_redirect(gid);
CREATE UNIQUE INDEX event_gid_redirect_gid ON event_gid_redirect(gid);
CREATE UNIQUE INDEX event_tag_pkey ON event_tag(event, tag);
CREATE UNIQUE INDEX event_type_gid ON event_type(gid);
CREATE UNIQUE INDEX gender_gid ON gender(gid);
CREATE UNIQUE INDEX genre_gid ON genre(gid);
CREATE UNIQUE INDEX genre_alias_type_gid ON genre_alias_type(gid);
CREATE UNIQUE INDEX genre_annotation_pkey ON genre_annotation(genre, annotation);
CREATE UNIQUE INDEX instrument_type_gid ON instrument_type(gid);
CREATE UNIQUE INDEX instrument_gid ON instrument(gid);
CREATE UNIQUE INDEX instrument_gid_redirect_pkey ON instrument_gid_redirect(gid);
CREATE UNIQUE INDEX instrument_gid_redirect_gid ON instrument_gid_redirect(gid);
CREATE UNIQUE INDEX instrument_alias_type_gid ON instrument_alias_type(gid);
CREATE UNIQUE INDEX instrument_annotation_pkey ON instrument_annotation(instrument, annotation);
CREATE UNIQUE INDEX instrument_attribute_type_gid ON instrument_attribute_type(gid);
CREATE UNIQUE INDEX instrument_attribute_type_allowed_value_gid ON instrument_attribute_type_allowed_value(gid);
CREATE UNIQUE INDEX instrument_tag_pkey ON instrument_tag(instrument, tag);
CREATE UNIQUE INDEX instrument_tag_raw_pkey ON instrument_tag_raw(instrument, editor, tag);
CREATE UNIQUE INDEX iso_3166_1_pkey ON iso_3166_1(code);
CREATE UNIQUE INDEX iso_3166_2_pkey ON iso_3166_2(code);
CREATE UNIQUE INDEX iso_3166_3_pkey ON iso_3166_3(code);
CREATE UNIQUE INDEX label_gid ON label(gid);
CREATE INDEX label_discogs_label_id ON label(discogs_label_id);
CREATE UNIQUE INDEX label_rating_raw_pkey ON label_rating_raw(label, editor);
CREATE UNIQUE INDEX label_tag_raw_pkey ON label_tag_raw(label, editor, tag);
CREATE UNIQUE INDEX label_alias_type_gid ON label_alias_type(gid);
CREATE UNIQUE INDEX label_annotation_pkey ON label_annotation(label, annotation);
CREATE UNIQUE INDEX label_attribute_type_gid ON label_attribute_type(gid);
CREATE UNIQUE INDEX label_attribute_type_allowed_value_gid ON label_attribute_type_allowed_value(gid);
CREATE UNIQUE INDEX label_ipi_pkey ON label_ipi(label, ipi);
CREATE UNIQUE INDEX label_isni_pkey ON label_isni(label, isni);
CREATE UNIQUE INDEX label_gid_redirect_pkey ON label_gid_redirect(gid);
CREATE UNIQUE INDEX label_gid_redirect_gid ON label_gid_redirect(gid);
CREATE UNIQUE INDEX label_tag_pkey ON label_tag(label, tag);
CREATE UNIQUE INDEX label_type_gid ON label_type(gid);
CREATE UNIQUE INDEX link_attribute_pkey ON link_attribute(link, attribute_type);
CREATE UNIQUE INDEX link_attribute_type_gid ON link_attribute_type(gid);
CREATE UNIQUE INDEX link_attribute_credit_pkey ON link_attribute_credit(link, attribute_type);
CREATE UNIQUE INDEX link_attribute_text_value_pkey ON link_attribute_text_value(link, attribute_type);
CREATE UNIQUE INDEX link_type_gid ON link_type(gid);
CREATE UNIQUE INDEX link_type_attribute_type_pkey ON link_type_attribute_type(link_type, attribute_type);
CREATE UNIQUE INDEX editor_collection_gid ON editor_collection(gid);
CREATE UNIQUE INDEX editor_collection_gid_redirect_pkey ON editor_collection_gid_redirect(gid);
CREATE UNIQUE INDEX editor_collection_gid_redirect_gid ON editor_collection_gid_redirect(gid);
CREATE UNIQUE INDEX editor_collection_type_gid ON editor_collection_type(gid);
CREATE UNIQUE INDEX editor_collection_collaborator_pkey ON editor_collection_collaborator(collection, editor);
CREATE UNIQUE INDEX editor_collection_area_pkey ON editor_collection_area(collection, area);
CREATE UNIQUE INDEX editor_collection_artist_pkey ON editor_collection_artist(collection, artist);
CREATE UNIQUE INDEX editor_collection_event_pkey ON editor_collection_event(collection, event);
CREATE UNIQUE INDEX editor_collection_genre_pkey ON editor_collection_genre(collection, genre);
CREATE UNIQUE INDEX editor_collection_instrument_pkey ON editor_collection_instrument(collection, instrument);
CREATE UNIQUE INDEX editor_collection_label_pkey ON editor_collection_label(collection, label);
CREATE UNIQUE INDEX editor_collection_place_pkey ON editor_collection_place(collection, place);
CREATE UNIQUE INDEX editor_collection_recording_pkey ON editor_collection_recording(collection, recording);
CREATE UNIQUE INDEX editor_collection_release_pkey ON editor_collection_release(collection, release);
CREATE UNIQUE INDEX editor_collection_release_group_pkey ON editor_collection_release_group(collection, release_group);
CREATE UNIQUE INDEX editor_collection_series_pkey ON editor_collection_series(collection, series);
CREATE UNIQUE INDEX editor_collection_work_pkey ON editor_collection_work(collection, work);
CREATE UNIQUE INDEX editor_collection_deleted_entity_pkey ON editor_collection_deleted_entity(collection, gid);
CREATE UNIQUE INDEX editor_collection_deleted_entity_gid ON editor_collection_deleted_entity(gid);
CREATE UNIQUE INDEX medium_gid ON medium(gid);
CREATE UNIQUE INDEX medium_attribute_type_gid ON medium_attribute_type(gid);
CREATE UNIQUE INDEX medium_attribute_type_allowed_format_pkey ON medium_attribute_type_allowed_format(medium_format, medium_attribute_type);
CREATE UNIQUE INDEX medium_attribute_type_allowed_value_gid ON medium_attribute_type_allowed_value(gid);
CREATE UNIQUE INDEX medium_attribute_type_allowed_value_allowed_format_pkey ON medium_attribute_type_allowed_value_allowed_format(medium_format, medium_attribute_type_allowed_value);
CREATE UNIQUE INDEX medium_format_gid ON medium_format(gid);
CREATE UNIQUE INDEX medium_gid_redirect_pkey ON medium_gid_redirect(gid);
CREATE UNIQUE INDEX medium_gid_redirect_gid ON medium_gid_redirect(gid);
CREATE UNIQUE INDEX mood_gid ON mood(gid);
CREATE UNIQUE INDEX mood_alias_type_gid ON mood_alias_type(gid);
CREATE UNIQUE INDEX mood_annotation_pkey ON mood_annotation(mood, annotation);
CREATE UNIQUE INDEX place_gid ON place(gid);
CREATE UNIQUE INDEX place_alias_type_gid ON place_alias_type(gid);
CREATE UNIQUE INDEX place_annotation_pkey ON place_annotation(place, annotation);
CREATE UNIQUE INDEX place_attribute_type_gid ON place_attribute_type(gid);
CREATE UNIQUE INDEX place_attribute_type_allowed_value_gid ON place_attribute_type_allowed_value(gid);
CREATE UNIQUE INDEX place_gid_redirect_pkey ON place_gid_redirect(gid);
CREATE UNIQUE INDEX place_gid_redirect_gid ON place_gid_redirect(gid);
CREATE UNIQUE INDEX place_rating_raw_pkey ON place_rating_raw(place, editor);
CREATE UNIQUE INDEX place_tag_pkey ON place_tag(place, tag);
CREATE UNIQUE INDEX place_tag_raw_pkey ON place_tag_raw(place, editor, tag);
CREATE UNIQUE INDEX place_type_gid ON place_type(gid);
CREATE UNIQUE INDEX recording_gid ON recording(gid);
CREATE UNIQUE INDEX recording_alias_type_gid ON recording_alias_type(gid);
CREATE UNIQUE INDEX recording_rating_raw_pkey ON recording_rating_raw(recording, editor);
CREATE UNIQUE INDEX recording_tag_raw_pkey ON recording_tag_raw(recording, editor, tag);
CREATE UNIQUE INDEX recording_annotation_pkey ON recording_annotation(recording, annotation);
CREATE UNIQUE INDEX recording_attribute_type_gid ON recording_attribute_type(gid);
CREATE UNIQUE INDEX recording_attribute_type_allowed_value_gid ON recording_attribute_type_allowed_value(gid);
CREATE UNIQUE INDEX recording_gid_redirect_pkey ON recording_gid_redirect(gid);
CREATE UNIQUE INDEX recording_gid_redirect_gid ON recording_gid_redirect(gid);
CREATE UNIQUE INDEX recording_tag_pkey ON recording_tag(recording, tag);
CREATE UNIQUE INDEX release_gid ON release(gid);
CREATE INDEX release_discogs_release_id ON release(discogs_release_id);
CREATE UNIQUE INDEX release_alias_type_gid ON release_alias_type(gid);
CREATE UNIQUE INDEX release_country_pkey ON release_country(release, country);
CREATE UNIQUE INDEX release_tag_raw_pkey ON release_tag_raw(release, editor, tag);
CREATE UNIQUE INDEX release_annotation_pkey ON release_annotation(release, annotation);
CREATE UNIQUE INDEX release_attribute_type_gid ON release_attribute_type(gid);
CREATE UNIQUE INDEX release_attribute_type_allowed_value_gid ON release_attribute_type_allowed_value(gid);
CREATE UNIQUE INDEX release_gid_redirect_pkey ON release_gid_redirect(gid);
CREATE UNIQUE INDEX release_gid_redirect_gid ON release_gid_redirect(gid);
CREATE UNIQUE INDEX release_packaging_gid ON release_packaging(gid);
CREATE UNIQUE INDEX release_status_gid ON release_status(gid);
CREATE UNIQUE INDEX release_tag_pkey ON release_tag(release, tag);
CREATE UNIQUE INDEX release_group_gid ON release_group(gid);
CREATE INDEX release_group_discogs_master_id ON release_group(discogs_master_id);
CREATE UNIQUE INDEX release_group_alias_type_gid ON release_group_alias_type(gid);
CREATE UNIQUE INDEX release_group_rating_raw_pkey ON release_group_rating_raw(release_group, editor);
CREATE UNIQUE INDEX release_group_tag_raw_pkey ON release_group_tag_raw(release_group, editor, tag);
CREATE UNIQUE INDEX release_group_annotation_pkey ON release_group_annotation(release_group, annotation);
CREATE UNIQUE INDEX release_group_attribute_type_gid ON release_group_attribute_type(gid);
CREATE UNIQUE INDEX release_group_attribute_type_allowed_value_gid ON release_group_attribute_type_allowed_value(gid);
CREATE UNIQUE INDEX release_group_gid_redirect_pkey ON release_group_gid_redirect(gid);
CREATE UNIQUE INDEX release_group_gid_redirect_gid ON release_group_gid_redirect(gid);
CREATE UNIQUE INDEX release_group_tag_pkey ON release_group_tag(release_group, tag);
CREATE UNIQUE INDEX release_group_primary_type_gid ON release_group_primary_type(gid);
CREATE UNIQUE INDEX release_group_secondary_type_gid ON release_group_secondary_type(gid);
CREATE UNIQUE INDEX release_group_secondary_type_join_pkey ON release_group_secondary_type_join(release_group, secondary_type);
CREATE UNIQUE INDEX series_gid ON series(gid);
CREATE UNIQUE INDEX series_type_gid ON series_type(gid);
CREATE UNIQUE INDEX series_ordering_type_gid ON series_ordering_type(gid);
CREATE UNIQUE INDEX series_gid_redirect_pkey ON series_gid_redirect(gid);
CREATE UNIQUE INDEX series_gid_redirect_gid ON series_gid_redirect(gid);
CREATE UNIQUE INDEX series_alias_type_gid ON series_alias_type(gid);
CREATE UNIQUE INDEX series_annotation_pkey ON series_annotation(series, annotation);
CREATE UNIQUE INDEX series_attribute_type_gid ON series_attribute_type(gid);
CREATE UNIQUE INDEX series_attribute_type_allowed_value_gid ON series_attribute_type_allowed_value(gid);
CREATE UNIQUE INDEX series_tag_pkey ON series_tag(series, tag);
CREATE UNIQUE INDEX series_tag_raw_pkey ON series_tag_raw(series, editor, tag);
CREATE UNIQUE INDEX tag_relation_pkey ON tag_relation(tag1, tag2);
CREATE UNIQUE INDEX track_gid ON track(gid);
CREATE UNIQUE INDEX track_gid_redirect_pkey ON track_gid_redirect(gid);
CREATE UNIQUE INDEX track_gid_redirect_gid ON track_gid_redirect(gid);
CREATE UNIQUE INDEX unreferenced_row_log_pkey ON unreferenced_row_log(table_name, row_id);
CREATE UNIQUE INDEX url_gid ON url(gid);
CREATE UNIQUE INDEX url_gid_redirect_pkey ON url_gid_redirect(gid);
CREATE UNIQUE INDEX url_gid_redirect_gid ON url_gid_redirect(gid);
CREATE UNIQUE INDEX work_gid ON work(gid);
CREATE UNIQUE INDEX work_language_pkey ON work_language(work, language);
CREATE UNIQUE INDEX work_rating_raw_pkey ON work_rating_raw(work, editor);
CREATE UNIQUE INDEX work_tag_raw_pkey ON work_tag_raw(work, editor, tag);
CREATE UNIQUE INDEX work_alias_type_gid ON work_alias_type(gid);
CREATE UNIQUE INDEX work_annotation_pkey ON work_annotation(work, annotation);
CREATE UNIQUE INDEX work_gid_redirect_pkey ON work_gid_redirect(gid);
CREATE UNIQUE INDEX work_gid_redirect_gid ON work_gid_redirect(gid);
CREATE UNIQUE INDEX work_tag_pkey ON work_tag(work, tag);
CREATE UNIQUE INDEX work_type_gid ON work_type(gid);
CREATE UNIQUE INDEX work_attribute_type_gid ON work_attribute_type(gid);
CREATE UNIQUE INDEX work_attribute_type_allowed_value_gid ON work_attribute_type_allowed_value(gid);
CREATE INDEX alternative_medium_alternative_release_idx ON alternative_medium(alternative_release);
CREATE INDEX alternative_medium_track_alternative_medium_idx ON alternative_medium_track(alternative_medium);
CREATE INDEX alternative_medium_track_alternative_track_idx ON alternative_medium_track(alternative_track);
CREATE INDEX alternative_medium_track_track_idx ON alternative_medium_track(track);
CREATE INDEX alternative_release_artist_credit_idx ON alternative_release(artist_credit);
CREATE INDEX alternative_release_language_idx ON alternative_release(language);
CREATE INDEX alternative_release_release_idx ON alternative_release(release);
CREATE INDEX alternative_release_script_idx ON alternative_release(script);
CREATE INDEX alternative_release_type_idx ON alternative_release(type);
CREATE INDEX alternative_release_type_parent_idx ON alternative_release_type(parent);
CREATE INDEX alternative_track_artist_credit_idx ON alternative_track(artist_credit);
CREATE INDEX annotation_editor_idx ON annotation(editor);
CREATE INDEX application_owner_idx ON application(owner);
CREATE INDEX area_type_idx ON area(type);
CREATE INDEX area_alias_area_idx ON area_alias(area);
CREATE INDEX area_alias_type_idx ON area_alias(type);
CREATE INDEX area_alias_type_parent_idx ON area_alias_type(parent);
CREATE INDEX area_annotation_annotation_idx ON area_annotation(annotation);
CREATE INDEX area_annotation_area_idx ON area_annotation(area);
CREATE INDEX area_attribute_area_idx ON area_attribute(area);
CREATE INDEX area_attribute_area_attribute_type_idx ON area_attribute(area_attribute_type);
CREATE INDEX area_attribute_area_attribute_type_allowed_value_idx ON area_attribute(area_attribute_type_allowed_value);
CREATE INDEX area_attribute_type_parent_idx ON area_attribute_type(parent);
CREATE INDEX area_attribute_type_allowed_value_area_attribute_type_idx ON area_attribute_type_allowed_value(area_attribute_type);
CREATE INDEX area_attribute_type_allowed_value_parent_idx ON area_attribute_type_allowed_value(parent);
CREATE INDEX area_containment_descendant_idx ON area_containment(descendant);
CREATE INDEX area_containment_parent_idx ON area_containment(parent);
CREATE INDEX area_gid_redirect_new_id_idx ON area_gid_redirect(new_id);
CREATE INDEX area_tag_area_idx ON area_tag(area);
CREATE INDEX area_tag_tag_idx ON area_tag(tag);
CREATE INDEX area_tag_raw_area_idx ON area_tag_raw(area);
CREATE INDEX area_tag_raw_editor_idx ON area_tag_raw(editor);
CREATE INDEX area_tag_raw_tag_idx ON area_tag_raw(tag);
CREATE INDEX area_type_parent_idx ON area_type(parent);
CREATE INDEX artist_area_idx ON artist(area);
CREATE INDEX artist_begin_area_idx ON artist(begin_area);
CREATE INDEX artist_end_area_idx ON artist(end_area);
CREATE INDEX artist_gender_idx ON artist(gender);
CREATE INDEX artist_type_idx ON artist(type);
CREATE INDEX artist_alias_artist_idx ON artist_alias(artist);
CREATE INDEX artist_alias_type_idx ON artist_alias(type);
CREATE INDEX artist_alias_type_parent_idx ON artist_alias_type(parent);
CREATE INDEX artist_annotation_annotation_idx ON artist_annotation(annotation);
CREATE INDEX artist_annotation_artist_idx ON artist_annotation(artist);
CREATE INDEX artist_attribute_artist_idx ON artist_attribute(artist);
CREATE INDEX artist_attribute_artist_attribute_type_idx ON artist_attribute(artist_attribute_type);
CREATE INDEX artist_attribute_artist_attribute_type_allowed_value_idx ON artist_attribute(artist_attribute_type_allowed_value);
CREATE INDEX artist_attribute_type_parent_idx ON artist_attribute_type(parent);
CREATE INDEX artist_attribute_type_allowed_value_artist_attribute_type_idx ON artist_attribute_type_allowed_value(artist_attribute_type);
CREATE INDEX artist_attribute_type_allowed_value_parent_idx ON artist_attribute_type_allowed_value(parent);
CREATE INDEX artist_credit_gid_redirect_new_id_idx ON artist_credit_gid_redirect(new_id);
CREATE INDEX artist_credit_name_artist_idx ON artist_credit_name(artist);
CREATE INDEX artist_credit_name_artist_credit_idx ON artist_credit_name(artist_credit);
CREATE INDEX artist_gid_redirect_new_id_idx ON artist_gid_redirect(new_id);
CREATE INDEX artist_ipi_artist_idx ON artist_ipi(artist);
CREATE INDEX artist_isni_artist_idx ON artist_isni(artist);
CREATE INDEX artist_meta_id_idx ON artist_meta(id);
CREATE INDEX artist_rating_raw_artist_idx ON artist_rating_raw(artist);
CREATE INDEX artist_rating_raw_editor_idx ON artist_rating_raw(editor);
CREATE INDEX artist_release_artist_idx ON artist_release(artist);
CREATE INDEX artist_release_release_idx ON artist_release(release);
CREATE INDEX artist_release_group_artist_idx ON artist_release_group(artist);
CREATE INDEX artist_release_group_release_group_idx ON artist_release_group(release_group);
CREATE INDEX artist_tag_artist_idx ON artist_tag(artist);
CREATE INDEX artist_tag_tag_idx ON artist_tag(tag);
CREATE INDEX artist_tag_raw_artist_idx ON artist_tag_raw(artist);
CREATE INDEX artist_tag_raw_editor_idx ON artist_tag_raw(editor);
CREATE INDEX artist_tag_raw_tag_idx ON artist_tag_raw(tag);
CREATE INDEX artist_type_parent_idx ON artist_type(parent);
CREATE INDEX autoeditor_election_candidate_idx ON autoeditor_election(candidate);
CREATE INDEX autoeditor_election_proposer_idx ON autoeditor_election(proposer);
CREATE INDEX autoeditor_election_seconder_1_idx ON autoeditor_election(seconder_1);
CREATE INDEX autoeditor_election_seconder_2_idx ON autoeditor_election(seconder_2);
CREATE INDEX autoeditor_election_vote_autoeditor_election_idx ON autoeditor_election_vote(autoeditor_election);
CREATE INDEX autoeditor_election_vote_voter_idx ON autoeditor_election_vote(voter);
CREATE INDEX cdtoc_raw_release_idx ON cdtoc_raw(release);
CREATE INDEX country_area_area_idx ON country_area(area);
CREATE INDEX edit_editor_idx ON edit(editor);
CREATE INDEX edit_language_idx ON edit(language);
CREATE INDEX edit_area_area_idx ON edit_area(area);
CREATE INDEX edit_area_edit_idx ON edit_area(edit);
CREATE INDEX edit_artist_artist_idx ON edit_artist(artist);
CREATE INDEX edit_artist_edit_idx ON edit_artist(edit);
CREATE INDEX edit_data_edit_idx ON edit_data(edit);
CREATE INDEX edit_event_edit_idx ON edit_event(edit);
CREATE INDEX edit_event_event_idx ON edit_event(event);
CREATE INDEX edit_genre_edit_idx ON edit_genre(edit);
CREATE INDEX edit_genre_genre_idx ON edit_genre(genre);
CREATE INDEX edit_instrument_edit_idx ON edit_instrument(edit);
CREATE INDEX edit_instrument_instrument_idx ON edit_instrument(instrument);
CREATE INDEX edit_label_edit_idx ON edit_label(edit);
CREATE INDEX edit_label_label_idx ON edit_label(label);
CREATE INDEX edit_mood_edit_idx ON edit_mood(edit);
CREATE INDEX edit_mood_mood_idx ON edit_mood(mood);
CREATE INDEX edit_note_edit_idx ON edit_note(edit);
CREATE INDEX edit_note_editor_idx ON edit_note(editor);
CREATE INDEX edit_note_change_change_editor_idx ON edit_note_change(change_editor);
CREATE INDEX edit_note_change_edit_note_idx ON edit_note_change(edit_note);
CREATE INDEX edit_note_recipient_edit_note_idx ON edit_note_recipient(edit_note);
CREATE INDEX edit_note_recipient_recipient_idx ON edit_note_recipient(recipient);
CREATE INDEX edit_place_edit_idx ON edit_place(edit);
CREATE INDEX edit_place_place_idx ON edit_place(place);
CREATE INDEX edit_recording_edit_idx ON edit_recording(edit);
CREATE INDEX edit_recording_recording_idx ON edit_recording(recording);
CREATE INDEX edit_release_edit_idx ON edit_release(edit);
CREATE INDEX edit_release_release_idx ON edit_release(release);
CREATE INDEX edit_release_group_edit_idx ON edit_release_group(edit);
CREATE INDEX edit_release_group_release_group_idx ON edit_release_group(release_group);
CREATE INDEX edit_series_edit_idx ON edit_series(edit);
CREATE INDEX edit_series_series_idx ON edit_series(series);
CREATE INDEX edit_url_edit_idx ON edit_url(edit);
CREATE INDEX edit_url_url_idx ON edit_url(url);
CREATE INDEX edit_work_edit_idx ON edit_work(edit);
CREATE INDEX edit_work_work_idx ON edit_work(work);
CREATE INDEX editor_area_idx ON editor(area);
CREATE INDEX editor_gender_idx ON editor(gender);
CREATE INDEX editor_collection_editor_idx ON editor_collection(editor);
CREATE INDEX editor_collection_type_idx ON editor_collection(type);
CREATE INDEX editor_collection_area_area_idx ON editor_collection_area(area);
CREATE INDEX editor_collection_area_collection_idx ON editor_collection_area(collection);
CREATE INDEX editor_collection_artist_artist_idx ON editor_collection_artist(artist);
CREATE INDEX editor_collection_artist_collection_idx ON editor_collection_artist(collection);
CREATE INDEX editor_collection_collaborator_collection_idx ON editor_collection_collaborator(collection);
CREATE INDEX editor_collection_collaborator_editor_idx ON editor_collection_collaborator(editor);
CREATE INDEX editor_collection_deleted_entity_collection_idx ON editor_collection_deleted_entity(collection);
CREATE INDEX editor_collection_deleted_entity_gid_idx ON editor_collection_deleted_entity(gid);
CREATE INDEX editor_collection_event_collection_idx ON editor_collection_event(collection);
CREATE INDEX editor_collection_event_event_idx ON editor_collection_event(event);
CREATE INDEX editor_collection_genre_collection_idx ON editor_collection_genre(collection);
CREATE INDEX editor_collection_genre_genre_idx ON editor_collection_genre(genre);
CREATE INDEX editor_collection_gid_redirect_new_id_idx ON editor_collection_gid_redirect(new_id);
CREATE INDEX editor_collection_instrument_collection_idx ON editor_collection_instrument(collection);
CREATE INDEX editor_collection_instrument_instrument_idx ON editor_collection_instrument(instrument);
CREATE INDEX editor_collection_label_collection_idx ON editor_collection_label(collection);
CREATE INDEX editor_collection_label_label_idx ON editor_collection_label(label);
CREATE INDEX editor_collection_place_collection_idx ON editor_collection_place(collection);
CREATE INDEX editor_collection_place_place_idx ON editor_collection_place(place);
CREATE INDEX editor_collection_recording_collection_idx ON editor_collection_recording(collection);
CREATE INDEX editor_collection_recording_recording_idx ON editor_collection_recording(recording);
CREATE INDEX editor_collection_release_collection_idx ON editor_collection_release(collection);
CREATE INDEX editor_collection_release_release_idx ON editor_collection_release(release);
CREATE INDEX editor_collection_release_group_collection_idx ON editor_collection_release_group(collection);
CREATE INDEX editor_collection_release_group_release_group_idx ON editor_collection_release_group(release_group);
CREATE INDEX editor_collection_series_collection_idx ON editor_collection_series(collection);
CREATE INDEX editor_collection_series_series_idx ON editor_collection_series(series);
CREATE INDEX editor_collection_type_parent_idx ON editor_collection_type(parent);
CREATE INDEX editor_collection_work_collection_idx ON editor_collection_work(collection);
CREATE INDEX editor_collection_work_work_idx ON editor_collection_work(work);
CREATE INDEX editor_language_editor_idx ON editor_language(editor);
CREATE INDEX editor_language_language_idx ON editor_language(language);
CREATE INDEX editor_oauth_token_application_idx ON editor_oauth_token(application);
CREATE INDEX editor_oauth_token_editor_idx ON editor_oauth_token(editor);
CREATE INDEX editor_preference_editor_idx ON editor_preference(editor);
CREATE INDEX editor_subscribe_artist_artist_idx ON editor_subscribe_artist(artist);
CREATE INDEX editor_subscribe_artist_editor_idx ON editor_subscribe_artist(editor);
CREATE INDEX editor_subscribe_artist_last_edit_sent_idx ON editor_subscribe_artist(last_edit_sent);
CREATE INDEX editor_subscribe_artist_deleted_deleted_by_idx ON editor_subscribe_artist_deleted(deleted_by);
CREATE INDEX editor_subscribe_artist_deleted_editor_idx ON editor_subscribe_artist_deleted(editor);
CREATE INDEX editor_subscribe_artist_deleted_gid_idx ON editor_subscribe_artist_deleted(gid);
CREATE INDEX editor_subscribe_collection_editor_idx ON editor_subscribe_collection(editor);
CREATE INDEX editor_subscribe_editor_editor_idx ON editor_subscribe_editor(editor);
CREATE INDEX editor_subscribe_editor_subscribed_editor_idx ON editor_subscribe_editor(subscribed_editor);
CREATE INDEX editor_subscribe_label_editor_idx ON editor_subscribe_label(editor);
CREATE INDEX editor_subscribe_label_label_idx ON editor_subscribe_label(label);
CREATE INDEX editor_subscribe_label_last_edit_sent_idx ON editor_subscribe_label(last_edit_sent);
CREATE INDEX editor_subscribe_label_deleted_deleted_by_idx ON editor_subscribe_label_deleted(deleted_by);
CREATE INDEX editor_subscribe_label_deleted_editor_idx ON editor_subscribe_label_deleted(editor);
CREATE INDEX editor_subscribe_label_deleted_gid_idx ON editor_subscribe_label_deleted(gid);
CREATE INDEX editor_subscribe_series_editor_idx ON editor_subscribe_series(editor);
CREATE INDEX editor_subscribe_series_last_edit_sent_idx ON editor_subscribe_series(last_edit_sent);
CREATE INDEX editor_subscribe_series_series_idx ON editor_subscribe_series(series);
CREATE INDEX editor_subscribe_series_deleted_deleted_by_idx ON editor_subscribe_series_deleted(deleted_by);
CREATE INDEX editor_subscribe_series_deleted_editor_idx ON editor_subscribe_series_deleted(editor);
CREATE INDEX editor_subscribe_series_deleted_gid_idx ON editor_subscribe_series_deleted(gid);
CREATE INDEX event_type_idx ON event(type);
CREATE INDEX event_alias_event_idx ON event_alias(event);
CREATE INDEX event_alias_type_idx ON event_alias(type);
CREATE INDEX event_alias_type_parent_idx ON event_alias_type(parent);
CREATE INDEX event_annotation_annotation_idx ON event_annotation(annotation);
CREATE INDEX event_annotation_event_idx ON event_annotation(event);
CREATE INDEX event_attribute_event_idx ON event_attribute(event);
CREATE INDEX event_attribute_event_attribute_type_idx ON event_attribute(event_attribute_type);
CREATE INDEX event_attribute_event_attribute_type_allowed_value_idx ON event_attribute(event_attribute_type_allowed_value);
CREATE INDEX event_attribute_type_parent_idx ON event_attribute_type(parent);
CREATE INDEX event_attribute_type_allowed_value_event_attribute_type_idx ON event_attribute_type_allowed_value(event_attribute_type);
CREATE INDEX event_attribute_type_allowed_value_parent_idx ON event_attribute_type_allowed_value(parent);
CREATE INDEX event_gid_redirect_new_id_idx ON event_gid_redirect(new_id);
CREATE INDEX event_meta_id_idx ON event_meta(id);
CREATE INDEX event_rating_raw_editor_idx ON event_rating_raw(editor);
CREATE INDEX event_rating_raw_event_idx ON event_rating_raw(event);
CREATE INDEX event_tag_event_idx ON event_tag(event);
CREATE INDEX event_tag_tag_idx ON event_tag(tag);
CREATE INDEX event_tag_raw_editor_idx ON event_tag_raw(editor);
CREATE INDEX event_tag_raw_event_idx ON event_tag_raw(event);
CREATE INDEX event_tag_raw_tag_idx ON event_tag_raw(tag);
CREATE INDEX event_type_parent_idx ON event_type(parent);
CREATE INDEX gender_parent_idx ON gender(parent);
CREATE INDEX genre_alias_genre_idx ON genre_alias(genre);
CREATE INDEX genre_alias_type_idx ON genre_alias(type);
CREATE INDEX genre_alias_type_parent_idx ON genre_alias_type(parent);
CREATE INDEX genre_annotation_annotation_idx ON genre_annotation(annotation);
CREATE INDEX genre_annotation_genre_idx ON genre_annotation(genre);
CREATE INDEX instrument_type_idx ON instrument(type);
CREATE INDEX instrument_alias_instrument_idx ON instrument_alias(instrument);
CREATE INDEX instrument_alias_type_idx ON instrument_alias(type);
CREATE INDEX instrument_alias_type_parent_idx ON instrument_alias_type(parent);
CREATE INDEX instrument_annotation_annotation_idx ON instrument_annotation(annotation);
CREATE INDEX instrument_annotation_instrument_idx ON instrument_annotation(instrument);
CREATE INDEX instrument_attribute_instrument_idx ON instrument_attribute(instrument);
CREATE INDEX instrument_attribute_instrument_attribute_type_idx ON instrument_attribute(instrument_attribute_type);
CREATE INDEX instrument_attribute_instrument_attribute_type_allowed_value_idx ON instrument_attribute(instrument_attribute_type_allowed_value);
CREATE INDEX instrument_attribute_type_parent_idx ON instrument_attribute_type(parent);
CREATE INDEX instrument_attribute_type_allowed_value_instrument_attribute_type_idx ON instrument_attribute_type_allowed_value(instrument_attribute_type);
CREATE INDEX instrument_attribute_type_allowed_value_parent_idx ON instrument_attribute_type_allowed_value(parent);
CREATE INDEX instrument_gid_redirect_new_id_idx ON instrument_gid_redirect(new_id);
CREATE INDEX instrument_tag_instrument_idx ON instrument_tag(instrument);
CREATE INDEX instrument_tag_tag_idx ON instrument_tag(tag);
CREATE INDEX instrument_tag_raw_editor_idx ON instrument_tag_raw(editor);
CREATE INDEX instrument_tag_raw_instrument_idx ON instrument_tag_raw(instrument);
CREATE INDEX instrument_tag_raw_tag_idx ON instrument_tag_raw(tag);
CREATE INDEX instrument_type_parent_idx ON instrument_type(parent);
CREATE INDEX iso_3166_1_area_idx ON iso_3166_1(area);
CREATE INDEX iso_3166_2_area_idx ON iso_3166_2(area);
CREATE INDEX iso_3166_3_area_idx ON iso_3166_3(area);
CREATE INDEX isrc_recording_idx ON isrc(recording);
CREATE INDEX iswc_work_idx ON iswc(work);
CREATE INDEX l_area_area_entity0_idx ON l_area_area(entity0);
CREATE INDEX l_area_area_entity1_idx ON l_area_area(entity1);
CREATE INDEX l_area_area_link_idx ON l_area_area(link);
CREATE INDEX l_area_artist_entity0_idx ON l_area_artist(entity0);
CREATE INDEX l_area_artist_entity1_idx ON l_area_artist(entity1);
CREATE INDEX l_area_artist_link_idx ON l_area_artist(link);
CREATE INDEX l_area_event_entity0_idx ON l_area_event(entity0);
CREATE INDEX l_area_event_entity1_idx ON l_area_event(entity1);
CREATE INDEX l_area_event_link_idx ON l_area_event(link);
CREATE INDEX l_area_genre_entity0_idx ON l_area_genre(entity0);
CREATE INDEX l_area_genre_entity1_idx ON l_area_genre(entity1);
CREATE INDEX l_area_genre_link_idx ON l_area_genre(link);
CREATE INDEX l_area_instrument_entity0_idx ON l_area_instrument(entity0);
CREATE INDEX l_area_instrument_entity1_idx ON l_area_instrument(entity1);
CREATE INDEX l_area_instrument_link_idx ON l_area_instrument(link);
CREATE INDEX l_area_label_entity0_idx ON l_area_label(entity0);
CREATE INDEX l_area_label_entity1_idx ON l_area_label(entity1);
CREATE INDEX l_area_label_link_idx ON l_area_label(link);
CREATE INDEX l_area_mood_entity0_idx ON l_area_mood(entity0);
CREATE INDEX l_area_mood_entity1_idx ON l_area_mood(entity1);
CREATE INDEX l_area_mood_link_idx ON l_area_mood(link);
CREATE INDEX l_area_place_entity0_idx ON l_area_place(entity0);
CREATE INDEX l_area_place_entity1_idx ON l_area_place(entity1);
CREATE INDEX l_area_place_link_idx ON l_area_place(link);
CREATE INDEX l_area_recording_entity0_idx ON l_area_recording(entity0);
CREATE INDEX l_area_recording_entity1_idx ON l_area_recording(entity1);
CREATE INDEX l_area_recording_link_idx ON l_area_recording(link);
CREATE INDEX l_area_release_entity0_idx ON l_area_release(entity0);
CREATE INDEX l_area_release_entity1_idx ON l_area_release(entity1);
CREATE INDEX l_area_release_link_idx ON l_area_release(link);
CREATE INDEX l_area_release_group_entity0_idx ON l_area_release_group(entity0);
CREATE INDEX l_area_release_group_entity1_idx ON l_area_release_group(entity1);
CREATE INDEX l_area_release_group_link_idx ON l_area_release_group(link);
CREATE INDEX l_area_series_entity0_idx ON l_area_series(entity0);
CREATE INDEX l_area_series_entity1_idx ON l_area_series(entity1);
CREATE INDEX l_area_series_link_idx ON l_area_series(link);
CREATE INDEX l_area_url_entity0_idx ON l_area_url(entity0);
CREATE INDEX l_area_url_entity1_idx ON l_area_url(entity1);
CREATE INDEX l_area_url_link_idx ON l_area_url(link);
CREATE INDEX l_area_work_entity0_idx ON l_area_work(entity0);
CREATE INDEX l_area_work_entity1_idx ON l_area_work(entity1);
CREATE INDEX l_area_work_link_idx ON l_area_work(link);
CREATE INDEX l_artist_artist_entity0_idx ON l_artist_artist(entity0);
CREATE INDEX l_artist_artist_entity1_idx ON l_artist_artist(entity1);
CREATE INDEX l_artist_artist_link_idx ON l_artist_artist(link);
CREATE INDEX l_artist_event_entity0_idx ON l_artist_event(entity0);
CREATE INDEX l_artist_event_entity1_idx ON l_artist_event(entity1);
CREATE INDEX l_artist_event_link_idx ON l_artist_event(link);
CREATE INDEX l_artist_genre_entity0_idx ON l_artist_genre(entity0);
CREATE INDEX l_artist_genre_entity1_idx ON l_artist_genre(entity1);
CREATE INDEX l_artist_genre_link_idx ON l_artist_genre(link);
CREATE INDEX l_artist_instrument_entity0_idx ON l_artist_instrument(entity0);
CREATE INDEX l_artist_instrument_entity1_idx ON l_artist_instrument(entity1);
CREATE INDEX l_artist_instrument_link_idx ON l_artist_instrument(link);
CREATE INDEX l_artist_label_entity0_idx ON l_artist_label(entity0);
CREATE INDEX l_artist_label_entity1_idx ON l_artist_label(entity1);
CREATE INDEX l_artist_label_link_idx ON l_artist_label(link);
CREATE INDEX l_artist_mood_entity0_idx ON l_artist_mood(entity0);
CREATE INDEX l_artist_mood_entity1_idx ON l_artist_mood(entity1);
CREATE INDEX l_artist_mood_link_idx ON l_artist_mood(link);
CREATE INDEX l_artist_place_entity0_idx ON l_artist_place(entity0);
CREATE INDEX l_artist_place_entity1_idx ON l_artist_place(entity1);
CREATE INDEX l_artist_place_link_idx ON l_artist_place(link);
CREATE INDEX l_artist_recording_entity0_idx ON l_artist_recording(entity0);
CREATE INDEX l_artist_recording_entity1_idx ON l_artist_recording(entity1);
CREATE INDEX l_artist_recording_link_idx ON l_artist_recording(link);
CREATE INDEX l_artist_release_entity0_idx ON l_artist_release(entity0);
CREATE INDEX l_artist_release_entity1_idx ON l_artist_release(entity1);
CREATE INDEX l_artist_release_link_idx ON l_artist_release(link);
CREATE INDEX l_artist_release_group_entity0_idx ON l_artist_release_group(entity0);
CREATE INDEX l_artist_release_group_entity1_idx ON l_artist_release_group(entity1);
CREATE INDEX l_artist_release_group_link_idx ON l_artist_release_group(link);
CREATE INDEX l_artist_series_entity0_idx ON l_artist_series(entity0);
CREATE INDEX l_artist_series_entity1_idx ON l_artist_series(entity1);
CREATE INDEX l_artist_series_link_idx ON l_artist_series(link);
CREATE INDEX l_artist_url_entity0_idx ON l_artist_url(entity0);
CREATE INDEX l_artist_url_entity1_idx ON l_artist_url(entity1);
CREATE INDEX l_artist_url_link_idx ON l_artist_url(link);
CREATE INDEX l_artist_work_entity0_idx ON l_artist_work(entity0);
CREATE INDEX l_artist_work_entity1_idx ON l_artist_work(entity1);
CREATE INDEX l_artist_work_link_idx ON l_artist_work(link);
CREATE INDEX l_event_event_entity0_idx ON l_event_event(entity0);
CREATE INDEX l_event_event_entity1_idx ON l_event_event(entity1);
CREATE INDEX l_event_event_link_idx ON l_event_event(link);
CREATE INDEX l_event_genre_entity0_idx ON l_event_genre(entity0);
CREATE INDEX l_event_genre_entity1_idx ON l_event_genre(entity1);
CREATE INDEX l_event_genre_link_idx ON l_event_genre(link);
CREATE INDEX l_event_instrument_entity0_idx ON l_event_instrument(entity0);
CREATE INDEX l_event_instrument_entity1_idx ON l_event_instrument(entity1);
CREATE INDEX l_event_instrument_link_idx ON l_event_instrument(link);
CREATE INDEX l_event_label_entity0_idx ON l_event_label(entity0);
CREATE INDEX l_event_label_entity1_idx ON l_event_label(entity1);
CREATE INDEX l_event_label_link_idx ON l_event_label(link);
CREATE INDEX l_event_mood_entity0_idx ON l_event_mood(entity0);
CREATE INDEX l_event_mood_entity1_idx ON l_event_mood(entity1);
CREATE INDEX l_event_mood_link_idx ON l_event_mood(link);
CREATE INDEX l_event_place_entity0_idx ON l_event_place(entity0);
CREATE INDEX l_event_place_entity1_idx ON l_event_place(entity1);
CREATE INDEX l_event_place_link_idx ON l_event_place(link);
CREATE INDEX l_event_recording_entity0_idx ON l_event_recording(entity0);
CREATE INDEX l_event_recording_entity1_idx ON l_event_recording(entity1);
CREATE INDEX l_event_recording_link_idx ON l_event_recording(link);
CREATE INDEX l_event_release_entity0_idx ON l_event_release(entity0);
CREATE INDEX l_event_release_entity1_idx ON l_event_release(entity1);
CREATE INDEX l_event_release_link_idx ON l_event_release(link);
CREATE INDEX l_event_release_group_entity0_idx ON l_event_release_group(entity0);
CREATE INDEX l_event_release_group_entity1_idx ON l_event_release_group(entity1);
CREATE INDEX l_event_release_group_link_idx ON l_event_release_group(link);
CREATE INDEX l_event_series_entity0_idx ON l_event_series(entity0);
CREATE INDEX l_event_series_entity1_idx ON l_event_series(entity1);
CREATE INDEX l_event_series_link_idx ON l_event_series(link);
CREATE INDEX l_event_url_entity0_idx ON l_event_url(entity0);
CREATE INDEX l_event_url_entity1_idx ON l_event_url(entity1);
CREATE INDEX l_event_url_link_idx ON l_event_url(link);
CREATE INDEX l_event_work_entity0_idx ON l_event_work(entity0);
CREATE INDEX l_event_work_entity1_idx ON l_event_work(entity1);
CREATE INDEX l_event_work_link_idx ON l_event_work(link);
CREATE INDEX l_genre_genre_entity0_idx ON l_genre_genre(entity0);
CREATE INDEX l_genre_genre_entity1_idx ON l_genre_genre(entity1);
CREATE INDEX l_genre_genre_link_idx ON l_genre_genre(link);
CREATE INDEX l_genre_instrument_entity0_idx ON l_genre_instrument(entity0);
CREATE INDEX l_genre_instrument_entity1_idx ON l_genre_instrument(entity1);
CREATE INDEX l_genre_instrument_link_idx ON l_genre_instrument(link);
CREATE INDEX l_genre_label_entity0_idx ON l_genre_label(entity0);
CREATE INDEX l_genre_label_entity1_idx ON l_genre_label(entity1);
CREATE INDEX l_genre_label_link_idx ON l_genre_label(link);
CREATE INDEX l_genre_mood_entity0_idx ON l_genre_mood(entity0);
CREATE INDEX l_genre_mood_entity1_idx ON l_genre_mood(entity1);
CREATE INDEX l_genre_mood_link_idx ON l_genre_mood(link);
CREATE INDEX l_genre_place_entity0_idx ON l_genre_place(entity0);
CREATE INDEX l_genre_place_entity1_idx ON l_genre_place(entity1);
CREATE INDEX l_genre_place_link_idx ON l_genre_place(link);
CREATE INDEX l_genre_recording_entity0_idx ON l_genre_recording(entity0);
CREATE INDEX l_genre_recording_entity1_idx ON l_genre_recording(entity1);
CREATE INDEX l_genre_recording_link_idx ON l_genre_recording(link);
CREATE INDEX l_genre_release_entity0_idx ON l_genre_release(entity0);
CREATE INDEX l_genre_release_entity1_idx ON l_genre_release(entity1);
CREATE INDEX l_genre_release_link_idx ON l_genre_release(link);
CREATE INDEX l_genre_release_group_entity0_idx ON l_genre_release_group(entity0);
CREATE INDEX l_genre_release_group_entity1_idx ON l_genre_release_group(entity1);
CREATE INDEX l_genre_release_group_link_idx ON l_genre_release_group(link);
CREATE INDEX l_genre_series_entity0_idx ON l_genre_series(entity0);
CREATE INDEX l_genre_series_entity1_idx ON l_genre_series(entity1);
CREATE INDEX l_genre_series_link_idx ON l_genre_series(link);
CREATE INDEX l_genre_url_entity0_idx ON l_genre_url(entity0);
CREATE INDEX l_genre_url_entity1_idx ON l_genre_url(entity1);
CREATE INDEX l_genre_url_link_idx ON l_genre_url(link);
CREATE INDEX l_genre_work_entity0_idx ON l_genre_work(entity0);
CREATE INDEX l_genre_work_entity1_idx ON l_genre_work(entity1);
CREATE INDEX l_genre_work_link_idx ON l_genre_work(link);
CREATE INDEX l_instrument_instrument_entity0_idx ON l_instrument_instrument(entity0);
CREATE INDEX l_instrument_instrument_entity1_idx ON l_instrument_instrument(entity1);
CREATE INDEX l_instrument_instrument_link_idx ON l_instrument_instrument(link);
CREATE INDEX l_instrument_label_entity0_idx ON l_instrument_label(entity0);
CREATE INDEX l_instrument_label_entity1_idx ON l_instrument_label(entity1);
CREATE INDEX l_instrument_label_link_idx ON l_instrument_label(link);
CREATE INDEX l_instrument_mood_entity0_idx ON l_instrument_mood(entity0);
CREATE INDEX l_instrument_mood_entity1_idx ON l_instrument_mood(entity1);
CREATE INDEX l_instrument_mood_link_idx ON l_instrument_mood(link);
CREATE INDEX l_instrument_place_entity0_idx ON l_instrument_place(entity0);
CREATE INDEX l_instrument_place_entity1_idx ON l_instrument_place(entity1);
CREATE INDEX l_instrument_place_link_idx ON l_instrument_place(link);
CREATE INDEX l_instrument_recording_entity0_idx ON l_instrument_recording(entity0);
CREATE INDEX l_instrument_recording_entity1_idx ON l_instrument_recording(entity1);
CREATE INDEX l_instrument_recording_link_idx ON l_instrument_recording(link);
CREATE INDEX l_instrument_release_entity0_idx ON l_instrument_release(entity0);
CREATE INDEX l_instrument_release_entity1_idx ON l_instrument_release(entity1);
CREATE INDEX l_instrument_release_link_idx ON l_instrument_release(link);
CREATE INDEX l_instrument_release_group_entity0_idx ON l_instrument_release_group(entity0);
CREATE INDEX l_instrument_release_group_entity1_idx ON l_instrument_release_group(entity1);
CREATE INDEX l_instrument_release_group_link_idx ON l_instrument_release_group(link);
CREATE INDEX l_instrument_series_entity0_idx ON l_instrument_series(entity0);
CREATE INDEX l_instrument_series_entity1_idx ON l_instrument_series(entity1);
CREATE INDEX l_instrument_series_link_idx ON l_instrument_series(link);
CREATE INDEX l_instrument_url_entity0_idx ON l_instrument_url(entity0);
CREATE INDEX l_instrument_url_entity1_idx ON l_instrument_url(entity1);
CREATE INDEX l_instrument_url_link_idx ON l_instrument_url(link);
CREATE INDEX l_instrument_work_entity0_idx ON l_instrument_work(entity0);
CREATE INDEX l_instrument_work_entity1_idx ON l_instrument_work(entity1);
CREATE INDEX l_instrument_work_link_idx ON l_instrument_work(link);
CREATE INDEX l_label_label_entity0_idx ON l_label_label(entity0);
CREATE INDEX l_label_label_entity1_idx ON l_label_label(entity1);
CREATE INDEX l_label_label_link_idx ON l_label_label(link);
CREATE INDEX l_label_mood_entity0_idx ON l_label_mood(entity0);
CREATE INDEX l_label_mood_entity1_idx ON l_label_mood(entity1);
CREATE INDEX l_label_mood_link_idx ON l_label_mood(link);
CREATE INDEX l_label_place_entity0_idx ON l_label_place(entity0);
CREATE INDEX l_label_place_entity1_idx ON l_label_place(entity1);
CREATE INDEX l_label_place_link_idx ON l_label_place(link);
CREATE INDEX l_label_recording_entity0_idx ON l_label_recording(entity0);
CREATE INDEX l_label_recording_entity1_idx ON l_label_recording(entity1);
CREATE INDEX l_label_recording_link_idx ON l_label_recording(link);
CREATE INDEX l_label_release_entity0_idx ON l_label_release(entity0);
CREATE INDEX l_label_release_entity1_idx ON l_label_release(entity1);
CREATE INDEX l_label_release_link_idx ON l_label_release(link);
CREATE INDEX l_label_release_group_entity0_idx ON l_label_release_group(entity0);
CREATE INDEX l_label_release_group_entity1_idx ON l_label_release_group(entity1);
CREATE INDEX l_label_release_group_link_idx ON l_label_release_group(link);
CREATE INDEX l_label_series_entity0_idx ON l_label_series(entity0);
CREATE INDEX l_label_series_entity1_idx ON l_label_series(entity1);
CREATE INDEX l_label_series_link_idx ON l_label_series(link);
CREATE INDEX l_label_url_entity0_idx ON l_label_url(entity0);
CREATE INDEX l_label_url_entity1_idx ON l_label_url(entity1);
CREATE INDEX l_label_url_link_idx ON l_label_url(link);
CREATE INDEX l_label_work_entity0_idx ON l_label_work(entity0);
CREATE INDEX l_label_work_entity1_idx ON l_label_work(entity1);
CREATE INDEX l_label_work_link_idx ON l_label_work(link);
CREATE INDEX l_mood_mood_entity0_idx ON l_mood_mood(entity0);
CREATE INDEX l_mood_mood_entity1_idx ON l_mood_mood(entity1);
CREATE INDEX l_mood_mood_link_idx ON l_mood_mood(link);
CREATE INDEX l_mood_place_entity0_idx ON l_mood_place(entity0);
CREATE INDEX l_mood_place_entity1_idx ON l_mood_place(entity1);
CREATE INDEX l_mood_place_link_idx ON l_mood_place(link);
CREATE INDEX l_mood_recording_entity0_idx ON l_mood_recording(entity0);
CREATE INDEX l_mood_recording_entity1_idx ON l_mood_recording(entity1);
CREATE INDEX l_mood_recording_link_idx ON l_mood_recording(link);
CREATE INDEX l_mood_release_entity0_idx ON l_mood_release(entity0);
CREATE INDEX l_mood_release_entity1_idx ON l_mood_release(entity1);
CREATE INDEX l_mood_release_link_idx ON l_mood_release(link);
CREATE INDEX l_mood_release_group_entity0_idx ON l_mood_release_group(entity0);
CREATE INDEX l_mood_release_group_entity1_idx ON l_mood_release_group(entity1);
CREATE INDEX l_mood_release_group_link_idx ON l_mood_release_group(link);
CREATE INDEX l_mood_series_entity0_idx ON l_mood_series(entity0);
CREATE INDEX l_mood_series_entity1_idx ON l_mood_series(entity1);
CREATE INDEX l_mood_series_link_idx ON l_mood_series(link);
CREATE INDEX l_mood_url_entity0_idx ON l_mood_url(entity0);
CREATE INDEX l_mood_url_entity1_idx ON l_mood_url(entity1);
CREATE INDEX l_mood_url_link_idx ON l_mood_url(link);
CREATE INDEX l_mood_work_entity0_idx ON l_mood_work(entity0);
CREATE INDEX l_mood_work_entity1_idx ON l_mood_work(entity1);
CREATE INDEX l_mood_work_link_idx ON l_mood_work(link);
CREATE INDEX l_place_place_entity0_idx ON l_place_place(entity0);
CREATE INDEX l_place_place_entity1_idx ON l_place_place(entity1);
CREATE INDEX l_place_place_link_idx ON l_place_place(link);
CREATE INDEX l_place_recording_entity0_idx ON l_place_recording(entity0);
CREATE INDEX l_place_recording_entity1_idx ON l_place_recording(entity1);
CREATE INDEX l_place_recording_link_idx ON l_place_recording(link);
CREATE INDEX l_place_release_entity0_idx ON l_place_release(entity0);
CREATE INDEX l_place_release_entity1_idx ON l_place_release(entity1);
CREATE INDEX l_place_release_link_idx ON l_place_release(link);
CREATE INDEX l_place_release_group_entity0_idx ON l_place_release_group(entity0);
CREATE INDEX l_place_release_group_entity1_idx ON l_place_release_group(entity1);
CREATE INDEX l_place_release_group_link_idx ON l_place_release_group(link);
CREATE INDEX l_place_series_entity0_idx ON l_place_series(entity0);
CREATE INDEX l_place_series_entity1_idx ON l_place_series(entity1);
CREATE INDEX l_place_series_link_idx ON l_place_series(link);
CREATE INDEX l_place_url_entity0_idx ON l_place_url(entity0);
CREATE INDEX l_place_url_entity1_idx ON l_place_url(entity1);
CREATE INDEX l_place_url_link_idx ON l_place_url(link);
CREATE INDEX l_place_work_entity0_idx ON l_place_work(entity0);
CREATE INDEX l_place_work_entity1_idx ON l_place_work(entity1);
CREATE INDEX l_place_work_link_idx ON l_place_work(link);
CREATE INDEX l_recording_recording_entity0_idx ON l_recording_recording(entity0);
CREATE INDEX l_recording_recording_entity1_idx ON l_recording_recording(entity1);
CREATE INDEX l_recording_recording_link_idx ON l_recording_recording(link);
CREATE INDEX l_recording_release_entity0_idx ON l_recording_release(entity0);
CREATE INDEX l_recording_release_entity1_idx ON l_recording_release(entity1);
CREATE INDEX l_recording_release_link_idx ON l_recording_release(link);
CREATE INDEX l_recording_release_group_entity0_idx ON l_recording_release_group(entity0);
CREATE INDEX l_recording_release_group_entity1_idx ON l_recording_release_group(entity1);
CREATE INDEX l_recording_release_group_link_idx ON l_recording_release_group(link);
CREATE INDEX l_recording_series_entity0_idx ON l_recording_series(entity0);
CREATE INDEX l_recording_series_entity1_idx ON l_recording_series(entity1);
CREATE INDEX l_recording_series_link_idx ON l_recording_series(link);
CREATE INDEX l_recording_url_entity0_idx ON l_recording_url(entity0);
CREATE INDEX l_recording_url_entity1_idx ON l_recording_url(entity1);
CREATE INDEX l_recording_url_link_idx ON l_recording_url(link);
CREATE INDEX l_recording_work_entity0_idx ON l_recording_work(entity0);
CREATE INDEX l_recording_work_entity1_idx ON l_recording_work(entity1);
CREATE INDEX l_recording_work_link_idx ON l_recording_work(link);
CREATE INDEX l_release_group_release_group_entity0_idx ON l_release_group_release_group(entity0);
CREATE INDEX l_release_group_release_group_entity1_idx ON l_release_group_release_group(entity1);
CREATE INDEX l_release_group_release_group_link_idx ON l_release_group_release_group(link);
CREATE INDEX l_release_group_series_entity0_idx ON l_release_group_series(entity0);
CREATE INDEX l_release_group_series_entity1_idx ON l_release_group_series(entity1);
CREATE INDEX l_release_group_series_link_idx ON l_release_group_series(link);
CREATE INDEX l_release_group_url_entity0_idx ON l_release_group_url(entity0);
CREATE INDEX l_release_group_url_entity1_idx ON l_release_group_url(entity1);
CREATE INDEX l_release_group_url_link_idx ON l_release_group_url(link);
CREATE INDEX l_release_group_work_entity0_idx ON l_release_group_work(entity0);
CREATE INDEX l_release_group_work_entity1_idx ON l_release_group_work(entity1);
CREATE INDEX l_release_group_work_link_idx ON l_release_group_work(link);
CREATE INDEX l_release_release_entity0_idx ON l_release_release(entity0);
CREATE INDEX l_release_release_entity1_idx ON l_release_release(entity1);
CREATE INDEX l_release_release_link_idx ON l_release_release(link);
CREATE INDEX l_release_release_group_entity0_idx ON l_release_release_group(entity0);
CREATE INDEX l_release_release_group_entity1_idx ON l_release_release_group(entity1);
CREATE INDEX l_release_release_group_link_idx ON l_release_release_group(link);
CREATE INDEX l_release_series_entity0_idx ON l_release_series(entity0);
CREATE INDEX l_release_series_entity1_idx ON l_release_series(entity1);
CREATE INDEX l_release_series_link_idx ON l_release_series(link);
CREATE INDEX l_release_url_entity0_idx ON l_release_url(entity0);
CREATE INDEX l_release_url_entity1_idx ON l_release_url(entity1);
CREATE INDEX l_release_url_link_idx ON l_release_url(link);
CREATE INDEX l_release_work_entity0_idx ON l_release_work(entity0);
CREATE INDEX l_release_work_entity1_idx ON l_release_work(entity1);
CREATE INDEX l_release_work_link_idx ON l_release_work(link);
CREATE INDEX l_series_series_entity0_idx ON l_series_series(entity0);
CREATE INDEX l_series_series_entity1_idx ON l_series_series(entity1);
CREATE INDEX l_series_series_link_idx ON l_series_series(link);
CREATE INDEX l_series_url_entity0_idx ON l_series_url(entity0);
CREATE INDEX l_series_url_entity1_idx ON l_series_url(entity1);
CREATE INDEX l_series_url_link_idx ON l_series_url(link);
CREATE INDEX l_series_work_entity0_idx ON l_series_work(entity0);
CREATE INDEX l_series_work_entity1_idx ON l_series_work(entity1);
CREATE INDEX l_series_work_link_idx ON l_series_work(link);
CREATE INDEX l_url_url_entity0_idx ON l_url_url(entity0);
CREATE INDEX l_url_url_entity1_idx ON l_url_url(entity1);
CREATE INDEX l_url_url_link_idx ON l_url_url(link);
CREATE INDEX l_url_work_entity0_idx ON l_url_work(entity0);
CREATE INDEX l_url_work_entity1_idx ON l_url_work(entity1);
CREATE INDEX l_url_work_link_idx ON l_url_work(link);
CREATE INDEX l_work_work_entity0_idx ON l_work_work(entity0);
CREATE INDEX l_work_work_entity1_idx ON l_work_work(entity1);
CREATE INDEX l_work_work_link_idx ON l_work_work(link);
CREATE INDEX label_area_idx ON label(area);
CREATE INDEX label_type_idx ON label(type);
CREATE INDEX label_alias_label_idx ON label_alias(label);
CREATE INDEX label_alias_type_idx ON label_alias(type);
CREATE INDEX label_alias_type_parent_idx ON label_alias_type(parent);
CREATE INDEX label_annotation_annotation_idx ON label_annotation(annotation);
CREATE INDEX label_annotation_label_idx ON label_annotation(label);
CREATE INDEX label_attribute_label_idx ON label_attribute(label);
CREATE INDEX label_attribute_label_attribute_type_idx ON label_attribute(label_attribute_type);
CREATE INDEX label_attribute_label_attribute_type_allowed_value_idx ON label_attribute(label_attribute_type_allowed_value);
CREATE INDEX label_attribute_type_parent_idx ON label_attribute_type(parent);
CREATE INDEX label_attribute_type_allowed_value_label_attribute_type_idx ON label_attribute_type_allowed_value(label_attribute_type);
CREATE INDEX label_attribute_type_allowed_value_parent_idx ON label_attribute_type_allowed_value(parent);
CREATE INDEX label_gid_redirect_new_id_idx ON label_gid_redirect(new_id);
CREATE INDEX label_ipi_label_idx ON label_ipi(label);
CREATE INDEX label_isni_label_idx ON label_isni(label);
CREATE INDEX label_meta_id_idx ON label_meta(id);
CREATE INDEX label_rating_raw_editor_idx ON label_rating_raw(editor);
CREATE INDEX label_rating_raw_label_idx ON label_rating_raw(label);
CREATE INDEX label_tag_label_idx ON label_tag(label);
CREATE INDEX label_tag_tag_idx ON label_tag(tag);
CREATE INDEX label_tag_raw_editor_idx ON label_tag_raw(editor);
CREATE INDEX label_tag_raw_label_idx ON label_tag_raw(label);
CREATE INDEX label_tag_raw_tag_idx ON label_tag_raw(tag);
CREATE INDEX label_type_parent_idx ON label_type(parent);
CREATE INDEX link_link_type_idx ON link(link_type);
CREATE INDEX link_attribute_attribute_type_idx ON link_attribute(attribute_type);
CREATE INDEX link_attribute_link_idx ON link_attribute(link);
CREATE INDEX link_attribute_credit_attribute_type_idx ON link_attribute_credit(attribute_type);
CREATE INDEX link_attribute_credit_link_idx ON link_attribute_credit(link);
CREATE INDEX link_attribute_text_value_attribute_type_idx ON link_attribute_text_value(attribute_type);
CREATE INDEX link_attribute_text_value_link_idx ON link_attribute_text_value(link);
CREATE INDEX link_attribute_type_parent_idx ON link_attribute_type(parent);
CREATE INDEX link_attribute_type_root_idx ON link_attribute_type(root);
CREATE INDEX link_creditable_attribute_type_attribute_type_idx ON link_creditable_attribute_type(attribute_type);
CREATE INDEX link_text_attribute_type_attribute_type_idx ON link_text_attribute_type(attribute_type);
CREATE INDEX link_type_parent_idx ON link_type(parent);
CREATE INDEX link_type_attribute_type_attribute_type_idx ON link_type_attribute_type(attribute_type);
CREATE INDEX link_type_attribute_type_link_type_idx ON link_type_attribute_type(link_type);
CREATE INDEX medium_format_idx ON medium(format);
CREATE INDEX medium_release_idx ON medium(release);
CREATE INDEX medium_attribute_medium_idx ON medium_attribute(medium);
CREATE INDEX medium_attribute_medium_attribute_type_idx ON medium_attribute(medium_attribute_type);
CREATE INDEX medium_attribute_medium_attribute_type_allowed_value_idx ON medium_attribute(medium_attribute_type_allowed_value);
CREATE INDEX medium_attribute_type_parent_idx ON medium_attribute_type(parent);
CREATE INDEX medium_attribute_type_allowed_format_medium_attribute_type_idx ON medium_attribute_type_allowed_format(medium_attribute_type);
CREATE INDEX medium_attribute_type_allowed_format_medium_format_idx ON medium_attribute_type_allowed_format(medium_format);
CREATE INDEX medium_attribute_type_allowed_value_medium_attribute_type_idx ON medium_attribute_type_allowed_value(medium_attribute_type);
CREATE INDEX medium_attribute_type_allowed_value_parent_idx ON medium_attribute_type_allowed_value(parent);
CREATE INDEX medium_attribute_type_allowed_value_allowed_format_medium_attribute_type_allowed_value_idx ON medium_attribute_type_allowed_value_allowed_format(medium_attribute_type_allowed_value);
CREATE INDEX medium_attribute_type_allowed_value_allowed_format_medium_format_idx ON medium_attribute_type_allowed_value_allowed_format(medium_format);
CREATE INDEX medium_cdtoc_cdtoc_idx ON medium_cdtoc(cdtoc);
CREATE INDEX medium_cdtoc_medium_idx ON medium_cdtoc(medium);
CREATE INDEX medium_format_parent_idx ON medium_format(parent);
CREATE INDEX medium_gid_redirect_new_id_idx ON medium_gid_redirect(new_id);
CREATE INDEX medium_index_medium_idx ON medium_index(medium);
CREATE INDEX mood_alias_mood_idx ON mood_alias(mood);
CREATE INDEX mood_alias_type_idx ON mood_alias(type);
CREATE INDEX mood_alias_type_parent_idx ON mood_alias_type(parent);
CREATE INDEX mood_annotation_annotation_idx ON mood_annotation(annotation);
CREATE INDEX mood_annotation_mood_idx ON mood_annotation(mood);
CREATE INDEX orderable_link_type_link_type_idx ON orderable_link_type(link_type);
CREATE INDEX place_area_idx ON place(area);
CREATE INDEX place_type_idx ON place(type);
CREATE INDEX place_alias_place_idx ON place_alias(place);
CREATE INDEX place_alias_type_idx ON place_alias(type);
CREATE INDEX place_alias_type_parent_idx ON place_alias_type(parent);
CREATE INDEX place_annotation_annotation_idx ON place_annotation(annotation);
CREATE INDEX place_annotation_place_idx ON place_annotation(place);
CREATE INDEX place_attribute_place_idx ON place_attribute(place);
CREATE INDEX place_attribute_place_attribute_type_idx ON place_attribute(place_attribute_type);
CREATE INDEX place_attribute_place_attribute_type_allowed_value_idx ON place_attribute(place_attribute_type_allowed_value);
CREATE INDEX place_attribute_type_parent_idx ON place_attribute_type(parent);
CREATE INDEX place_attribute_type_allowed_value_parent_idx ON place_attribute_type_allowed_value(parent);
CREATE INDEX place_attribute_type_allowed_value_place_attribute_type_idx ON place_attribute_type_allowed_value(place_attribute_type);
CREATE INDEX place_gid_redirect_new_id_idx ON place_gid_redirect(new_id);
CREATE INDEX place_meta_id_idx ON place_meta(id);
CREATE INDEX place_rating_raw_editor_idx ON place_rating_raw(editor);
CREATE INDEX place_rating_raw_place_idx ON place_rating_raw(place);
CREATE INDEX place_tag_place_idx ON place_tag(place);
CREATE INDEX place_tag_tag_idx ON place_tag(tag);
CREATE INDEX place_tag_raw_editor_idx ON place_tag_raw(editor);
CREATE INDEX place_tag_raw_place_idx ON place_tag_raw(place);
CREATE INDEX place_tag_raw_tag_idx ON place_tag_raw(tag);
CREATE INDEX place_type_parent_idx ON place_type(parent);
CREATE INDEX recording_artist_credit_idx ON recording(artist_credit);
CREATE INDEX recording_alias_recording_idx ON recording_alias(recording);
CREATE INDEX recording_alias_type_idx ON recording_alias(type);
CREATE INDEX recording_alias_type_parent_idx ON recording_alias_type(parent);
CREATE INDEX recording_annotation_annotation_idx ON recording_annotation(annotation);
CREATE INDEX recording_annotation_recording_idx ON recording_annotation(recording);
CREATE INDEX recording_attribute_recording_idx ON recording_attribute(recording);
CREATE INDEX recording_attribute_recording_attribute_type_idx ON recording_attribute(recording_attribute_type);
CREATE INDEX recording_attribute_recording_attribute_type_allowed_value_idx ON recording_attribute(recording_attribute_type_allowed_value);
CREATE INDEX recording_attribute_type_parent_idx ON recording_attribute_type(parent);
CREATE INDEX recording_attribute_type_allowed_value_parent_idx ON recording_attribute_type_allowed_value(parent);
CREATE INDEX recording_attribute_type_allowed_value_recording_attribute_type_idx ON recording_attribute_type_allowed_value(recording_attribute_type);
CREATE INDEX recording_first_release_date_recording_idx ON recording_first_release_date(recording);
CREATE INDEX recording_gid_redirect_new_id_idx ON recording_gid_redirect(new_id);
CREATE INDEX recording_meta_id_idx ON recording_meta(id);
CREATE INDEX recording_rating_raw_editor_idx ON recording_rating_raw(editor);
CREATE INDEX recording_rating_raw_recording_idx ON recording_rating_raw(recording);
CREATE INDEX recording_tag_recording_idx ON recording_tag(recording);
CREATE INDEX recording_tag_tag_idx ON recording_tag(tag);
CREATE INDEX recording_tag_raw_editor_idx ON recording_tag_raw(editor);
CREATE INDEX recording_tag_raw_recording_idx ON recording_tag_raw(recording);
CREATE INDEX recording_tag_raw_tag_idx ON recording_tag_raw(tag);
CREATE INDEX release_artist_credit_idx ON release(artist_credit);
CREATE INDEX release_language_idx ON release(language);
CREATE INDEX release_packaging_idx ON release(packaging);
CREATE INDEX release_release_group_idx ON release(release_group);
CREATE INDEX release_script_idx ON release(script);
CREATE INDEX release_status_idx ON release(status);
CREATE INDEX release_alias_release_idx ON release_alias(release);
CREATE INDEX release_alias_type_idx ON release_alias(type);
CREATE INDEX release_alias_type_parent_idx ON release_alias_type(parent);
CREATE INDEX release_annotation_annotation_idx ON release_annotation(annotation);
CREATE INDEX release_annotation_release_idx ON release_annotation(release);
CREATE INDEX release_attribute_release_idx ON release_attribute(release);
CREATE INDEX release_attribute_release_attribute_type_idx ON release_attribute(release_attribute_type);
CREATE INDEX release_attribute_release_attribute_type_allowed_value_idx ON release_attribute(release_attribute_type_allowed_value);
CREATE INDEX release_attribute_type_parent_idx ON release_attribute_type(parent);
CREATE INDEX release_attribute_type_allowed_value_parent_idx ON release_attribute_type_allowed_value(parent);
CREATE INDEX release_attribute_type_allowed_value_release_attribute_type_idx ON release_attribute_type_allowed_value(release_attribute_type);
CREATE INDEX release_country_country_idx ON release_country(country);
CREATE INDEX release_country_release_idx ON release_country(release);
CREATE INDEX release_first_release_date_release_idx ON release_first_release_date(release);
CREATE INDEX release_gid_redirect_new_id_idx ON release_gid_redirect(new_id);
CREATE INDEX release_group_artist_credit_idx ON release_group(artist_credit);
CREATE INDEX release_group_type_idx ON release_group(type);
CREATE INDEX release_group_alias_release_group_idx ON release_group_alias(release_group);
CREATE INDEX release_group_alias_type_idx ON release_group_alias(type);
CREATE INDEX release_group_alias_type_parent_idx ON release_group_alias_type(parent);
CREATE INDEX release_group_annotation_annotation_idx ON release_group_annotation(annotation);
CREATE INDEX release_group_annotation_release_group_idx ON release_group_annotation(release_group);
CREATE INDEX release_group_attribute_release_group_idx ON release_group_attribute(release_group);
CREATE INDEX release_group_attribute_release_group_attribute_type_idx ON release_group_attribute(release_group_attribute_type);
CREATE INDEX release_group_attribute_release_group_attribute_type_allowed_value_idx ON release_group_attribute(release_group_attribute_type_allowed_value);
CREATE INDEX release_group_attribute_type_parent_idx ON release_group_attribute_type(parent);
CREATE INDEX release_group_attribute_type_allowed_value_parent_idx ON release_group_attribute_type_allowed_value(parent);
CREATE INDEX release_group_attribute_type_allowed_value_release_group_attribute_type_idx ON release_group_attribute_type_allowed_value(release_group_attribute_type);
CREATE INDEX release_group_gid_redirect_new_id_idx ON release_group_gid_redirect(new_id);
CREATE INDEX release_group_meta_id_idx ON release_group_meta(id);
CREATE INDEX release_group_primary_type_parent_idx ON release_group_primary_type(parent);
CREATE INDEX release_group_rating_raw_editor_idx ON release_group_rating_raw(editor);
CREATE INDEX release_group_rating_raw_release_group_idx ON release_group_rating_raw(release_group);
CREATE INDEX release_group_secondary_type_parent_idx ON release_group_secondary_type(parent);
CREATE INDEX release_group_secondary_type_join_release_group_idx ON release_group_secondary_type_join(release_group);
CREATE INDEX release_group_secondary_type_join_secondary_type_idx ON release_group_secondary_type_join(secondary_type);
CREATE INDEX release_group_tag_release_group_idx ON release_group_tag(release_group);
CREATE INDEX release_group_tag_tag_idx ON release_group_tag(tag);
CREATE INDEX release_group_tag_raw_editor_idx ON release_group_tag_raw(editor);
CREATE INDEX release_group_tag_raw_release_group_idx ON release_group_tag_raw(release_group);
CREATE INDEX release_group_tag_raw_tag_idx ON release_group_tag_raw(tag);
CREATE INDEX release_label_label_idx ON release_label(label);
CREATE INDEX release_label_release_idx ON release_label(release);
CREATE INDEX release_meta_id_idx ON release_meta(id);
CREATE INDEX release_packaging_parent_idx ON release_packaging(parent);
CREATE INDEX release_status_parent_idx ON release_status(parent);
CREATE INDEX release_tag_release_idx ON release_tag(release);
CREATE INDEX release_tag_tag_idx ON release_tag(tag);
CREATE INDEX release_tag_raw_editor_idx ON release_tag_raw(editor);
CREATE INDEX release_tag_raw_release_idx ON release_tag_raw(release);
CREATE INDEX release_tag_raw_tag_idx ON release_tag_raw(tag);
CREATE INDEX release_unknown_country_release_idx ON release_unknown_country(release);
CREATE INDEX series_ordering_type_idx ON series(ordering_type);
CREATE INDEX series_type_idx ON series(type);
CREATE INDEX series_alias_series_idx ON series_alias(series);
CREATE INDEX series_alias_type_idx ON series_alias(type);
CREATE INDEX series_alias_type_parent_idx ON series_alias_type(parent);
CREATE INDEX series_annotation_annotation_idx ON series_annotation(annotation);
CREATE INDEX series_annotation_series_idx ON series_annotation(series);
CREATE INDEX series_attribute_series_idx ON series_attribute(series);
CREATE INDEX series_attribute_series_attribute_type_idx ON series_attribute(series_attribute_type);
CREATE INDEX series_attribute_series_attribute_type_allowed_value_idx ON series_attribute(series_attribute_type_allowed_value);
CREATE INDEX series_attribute_type_parent_idx ON series_attribute_type(parent);
CREATE INDEX series_attribute_type_allowed_value_parent_idx ON series_attribute_type_allowed_value(parent);
CREATE INDEX series_attribute_type_allowed_value_series_attribute_type_idx ON series_attribute_type_allowed_value(series_attribute_type);
CREATE INDEX series_gid_redirect_new_id_idx ON series_gid_redirect(new_id);
CREATE INDEX series_ordering_type_parent_idx ON series_ordering_type(parent);
CREATE INDEX series_tag_series_idx ON series_tag(series);
CREATE INDEX series_tag_tag_idx ON series_tag(tag);
CREATE INDEX series_tag_raw_editor_idx ON series_tag_raw(editor);
CREATE INDEX series_tag_raw_series_idx ON series_tag_raw(series);
CREATE INDEX series_tag_raw_tag_idx ON series_tag_raw(tag);
CREATE INDEX series_type_parent_idx ON series_type(parent);
CREATE INDEX tag_relation_tag1_idx ON tag_relation(tag1);
CREATE INDEX tag_relation_tag2_idx ON tag_relation(tag2);
CREATE INDEX track_artist_credit_idx ON track(artist_credit);
CREATE INDEX track_medium_idx ON track(medium);
CREATE INDEX track_recording_idx ON track(recording);
CREATE INDEX track_gid_redirect_new_id_idx ON track_gid_redirect(new_id);
CREATE INDEX track_raw_release_idx ON track_raw(release);
CREATE INDEX url_gid_redirect_new_id_idx ON url_gid_redirect(new_id);
CREATE INDEX vote_edit_idx ON vote(edit);
CREATE INDEX vote_editor_idx ON vote(editor);
CREATE INDEX work_type_idx ON work(type);
CREATE INDEX work_alias_type_idx ON work_alias(type);
CREATE INDEX work_alias_work_idx ON work_alias(work);
CREATE INDEX work_alias_type_parent_idx ON work_alias_type(parent);
CREATE INDEX work_annotation_annotation_idx ON work_annotation(annotation);
CREATE INDEX work_annotation_work_idx ON work_annotation(work);
CREATE INDEX work_attribute_work_idx ON work_attribute(work);
CREATE INDEX work_attribute_work_attribute_type_idx ON work_attribute(work_attribute_type);
CREATE INDEX work_attribute_work_attribute_type_allowed_value_idx ON work_attribute(work_attribute_type_allowed_value);
CREATE INDEX work_attribute_type_parent_idx ON work_attribute_type(parent);
CREATE INDEX work_attribute_type_allowed_value_parent_idx ON work_attribute_type_allowed_value(parent);
CREATE INDEX work_attribute_type_allowed_value_work_attribute_type_idx ON work_attribute_type_allowed_value(work_attribute_type);
CREATE INDEX work_gid_redirect_new_id_idx ON work_gid_redirect(new_id);
CREATE INDEX work_language_language_idx ON work_language(language);
CREATE INDEX work_language_work_idx ON work_language(work);
CREATE INDEX work_meta_id_idx ON work_meta(id);
CREATE INDEX work_rating_raw_editor_idx ON work_rating_raw(editor);
CREATE INDEX work_rating_raw_work_idx ON work_rating_raw(work);
CREATE INDEX work_tag_tag_idx ON work_tag(tag);
CREATE INDEX work_tag_work_idx ON work_tag(work);
CREATE INDEX work_tag_raw_editor_idx ON work_tag_raw(editor);
CREATE INDEX work_tag_raw_tag_idx ON work_tag_raw(tag);
CREATE INDEX work_tag_raw_work_idx ON work_tag_raw(work);
CREATE INDEX work_type_parent_idx ON work_type(parent);
